export MM_SERVICESETTINGS_LISTENADDRESS="0.0.0.0:${PORT}"
export MM_SERVICESETTINGS_SITEURL="https://${RAILWAY_STATIC_URL}"
export MM_SQLSETTINGS_DATASOURCE=${DATABASE_URL}
export MM_FILE_SETTINGS_DRIVER_NAME=local
export MM_LOGSETTINGS_ENABLECONSOLE=true
export MM_PLUGINSETTINGS_CLIENTDIRECTORY="./mattermost/client/plugins"

./mattermost/bin/mattermost